### ISSUE TITLE
Can't seem to locate the file for OpenWRT?

### ISSUE THREAD

**Issue by the-wazir** [aidanmacgregor/EE_WiFi-BT_WiFi-Autologin-OpenWRT#2]
Hi there.  I'm really interested to try out your project and have been looking for the tar file to install in OpenWRT but I can't find anything at the moment.  I'm possibly being super dumb and missing it somewhere, I'd really appreciate a link to where I can download the file for OpenWRT.  Thanks :)

**Comment by aidanmacgregor** [comment]
oh, sorry seems for v5 i messed up and uploaded the file by itself rather than the backup tar.gz, will look at reuploading :)

**Comment by aidanmacgregor** [comment]
should be up as v6 now :)

**Comment by the-wazir** [comment]
Hey, many thanks for that - much appreciated! :D
